"""Independent Region Research package for AD Skin Tool."""

from ad_skin_tools.region_research.boundary_contacts import (
    BoundaryContactResearchResult,
    BoundaryOwnerContact,
    SecondaryRegionBoundary,
    analyze_secondary_region_boundaries,
)
from ad_skin_tools.region_research.exact_tie_resolution import (
    ExactTieResolutionResult,
    RESOLVED_BY_FEWER_OWNED_VERTICES,
    RESOLVED_BY_STABLE_JOINT_KEY,
    RESOLVED_BY_TOPOLOGY,
    resolve_exact_ties,
)
from ad_skin_tools.region_research.multiple_candidate_reassignment import (
    MultipleCandidateProposal,
    MultipleCandidateReassignmentResult,
    MultipleCandidateScore,
    RESOLUTION_AGGREGATE_DISTANCE,
    RESOLUTION_CONTACT_EDGE_COUNT,
    RESOLUTION_FEWER_OWNED_VERTICES,
    RESOLUTION_STABLE_JOINT_KEY,
    propose_multiple_candidate_reassignments,
)
from ad_skin_tools.region_research.nearest_regions import (
    DEFAULT_DISTANCE_CHUNK_SIZE,
    NearestRegionResearchResult,
    solve_nearest_regions,
)
from ad_skin_tools.region_research.runner import (
    get_last_result,
    get_last_stage_01_result,
    get_last_stage_02_result,
    get_last_stage_03_result,
    get_last_stage_04_result,
    print_stage_01_report,
    print_stage_02_report,
    print_stage_03_report,
    print_stage_04_report,
    run_stage_01,
    run_stage_02,
    run_stage_02_from_stage_01,
    run_stage_03,
    run_stage_03_from_stage_02,
    run_stage_04,
    run_stage_04_from_stage_03,
)
from ad_skin_tools.region_research.single_candidate_reassignment import (
    DeferredSecondaryRegion,
    SingleCandidateProposal,
    SingleCandidateReassignmentResult,
    propose_single_candidate_reassignments,
)


__all__ = [
    "BoundaryContactResearchResult",
    "BoundaryOwnerContact",
    "DEFAULT_DISTANCE_CHUNK_SIZE",
    "DeferredSecondaryRegion",
    "ExactTieResolutionResult",
    "MultipleCandidateProposal",
    "MultipleCandidateReassignmentResult",
    "MultipleCandidateScore",
    "NearestRegionResearchResult",
    "RESOLVED_BY_FEWER_OWNED_VERTICES",
    "RESOLVED_BY_STABLE_JOINT_KEY",
    "RESOLVED_BY_TOPOLOGY",
    "RESOLUTION_AGGREGATE_DISTANCE",
    "RESOLUTION_CONTACT_EDGE_COUNT",
    "RESOLUTION_FEWER_OWNED_VERTICES",
    "RESOLUTION_STABLE_JOINT_KEY",
    "SecondaryRegionBoundary",
    "SingleCandidateProposal",
    "SingleCandidateReassignmentResult",
    "analyze_secondary_region_boundaries",
    "get_last_result",
    "get_last_stage_01_result",
    "get_last_stage_02_result",
    "get_last_stage_03_result",
    "get_last_stage_04_result",
    "print_stage_01_report",
    "print_stage_02_report",
    "print_stage_03_report",
    "print_stage_04_report",
    "propose_multiple_candidate_reassignments",
    "propose_single_candidate_reassignments",
    "resolve_exact_ties",
    "run_stage_01",
    "run_stage_02",
    "run_stage_02_from_stage_01",
    "run_stage_03",
    "run_stage_03_from_stage_02",
    "run_stage_04",
    "run_stage_04_from_stage_03",
    "solve_nearest_regions",
]
