from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence, Set, Tuple
import time

import maya.api.OpenMaya as om
import maya.cmds as cmds

from ad_skin_tools.core.compat import ensure_numpy
from ad_skin_tools.core.joint_surface_solver import JointSeedResult
from ad_skin_tools.core.mesh import (
    get_dag_path,
    get_vertex_count,
    get_vertex_normals,
    get_vertex_positions,
    get_weighted_vertex_neighbors,
    get_world_positions,
)

np = ensure_numpy()


@dataclass(frozen=True)
class JointCompetitionOptions:
    """
    AD Skin Tool v2.6 Phase 2.1.

    Every raw surface candidate is evaluated against every joint.

    No joint hierarchy, parent-child relation, or bone segment is used.
    """

    # Joint should normally be behind the outward vertex normal.
    #
    # -1.0 = directly inward
    #  0.0 = tangent
    # +1.0 = outward
    inward_dot_threshold: float = 0.10

    # Secondary preference after world-space joint distance.
    normal_alignment_weight: float = 0.35

    # Hard line-of-sight validation:
    #
    # joint -> candidate vertex
    #
    # The first mesh intersection must belong to a face connected
    # to the target vertex.
    require_visibility: bool = True

    ray_tolerance: float = 1e-6

    # Numerical distance tolerance is based on the local mesh edge length.
    visibility_tolerance_fraction: float = 0.15
    minimum_visibility_tolerance: float = 1e-4

    minimum_resolved_seed_count: int = 4

    # False is useful during research because all joint diagnostics and
    # seed sets remain available even when one joint receives few seeds.
    fail_on_invalid_joint: bool = False


@dataclass(frozen=True)
class JointCompetitionDiagnostic:
    joint: str

    raw_candidate_count: int

    strict_visible_raw_count: int
    relaxed_visible_raw_count: int

    won_before_component_filter: int
    resolved_seed_count: int
    removed_disconnected_count: int

    anchor_vertex_id: int
    anchor_mode: str
    anchor_score: float

    valid: bool
    messages: Tuple[str, ...]


@dataclass(frozen=True)
class CompetitiveSeedResult:
    mesh_shape: str
    influences: Tuple[str, ...]

    resolved_seed_vertex_ids: Dict[
        str,
        Tuple[int, ...],
    ]

    anchor_vertex_ids: Dict[
        str,
        int,
    ]

    diagnostics: Tuple[
        JointCompetitionDiagnostic,
        ...,
    ]

    raw_unique_candidate_count: int
    resolved_unique_seed_count: int

    visibility_test_count: int
    visibility_fallback_vertex_count: int

    elapsed_seconds: float


def resolve_joint_seed_competition(
    seed_result: JointSeedResult,
    options: Optional[JointCompetitionOptions] = None,
) -> CompetitiveSeedResult:
    """
    Resolve raw radial candidates through global joint competition.

    Important difference from the previous resolver:

    A candidate originally generated by ring_001 is still compared with
    pinky_001, hand_BND, and every other joint.

    Therefore a pinky-area candidate cannot remain with ring_001 merely
    because pinky_001 did not generate that exact candidate vertex.
    """
    started = time.perf_counter()

    options = options or JointCompetitionOptions()
    _validate_options(options)

    mesh_shape = seed_result.mesh_shape

    if not mesh_shape or not cmds.objExists(mesh_shape):
        raise RuntimeError(
            "The mesh from the Phase-1 result no longer exists."
        )

    influences = tuple(seed_result.influences)

    if len(influences) < 2:
        raise RuntimeError(
            "At least two joints are required."
        )

    vertex_count = get_vertex_count(mesh_shape)

    if vertex_count <= 0:
        raise RuntimeError(
            "The mesh contains no vertices."
        )

    vertex_ids = np.arange(
        vertex_count,
        dtype=np.int32,
    )

    positions = get_vertex_positions(
        mesh_shape,
        vertex_ids,
    )

    normals = get_vertex_normals(
        mesh_shape,
        vertex_ids,
    )

    adjacency = get_weighted_vertex_neighbors(
        mesh_shape
    )

    joint_positions = get_world_positions(
        list(influences)
    )

    raw_by_joint: List[Set[int]] = []

    raw_union: Set[int] = set()

    for joint in influences:
        raw_candidates = {
            int(vertex_id)
            for vertex_id
            in seed_result.seed_vertex_ids.get(
                joint,
                (),
            )
        }

        if not raw_candidates:
            raise RuntimeError(
                "Joint has no Phase-1 candidates:\n{}".format(
                    joint
                )
            )

        _validate_vertex_ids(
            vertex_ids=raw_candidates,
            vertex_count=vertex_count,
            joint=joint,
        )

        raw_by_joint.append(
            raw_candidates
        )

        raw_union.update(
            raw_candidates
        )

    union_ids = np.asarray(
        sorted(raw_union),
        dtype=np.int32,
    )

    union_row_by_vertex = {
        int(vertex_id): row
        for row, vertex_id
        in enumerate(union_ids)
    }

    union_positions = positions[
        union_ids
    ]

    union_normals = normals[
        union_ids
    ]

    scores, inward_dots = _build_score_matrices(
        vertex_positions=union_positions,
        vertex_normals=union_normals,
        joint_positions=joint_positions,
        normal_alignment_weight=float(
            options.normal_alignment_weight
        ),
    )

    local_edge_scales = _local_edge_scales(
        adjacency
    )

    mesh_dag_path = get_dag_path(
        mesh_shape
    )

    mesh_fn = om.MFnMesh(
        mesh_dag_path
    )

    accel_params = mesh_fn.autoUniformGridParams()

    connected_faces = _connected_faces_by_vertex(
        mesh_dag_path,
        vertex_count,
    )

    visibility = np.ones(
        (
            len(union_ids),
            len(influences),
        ),
        dtype=bool,
    )

    visibility_test_count = 0

    try:
        if options.require_visibility:
            visibility.fill(False)

            for union_row, vertex_id in enumerate(
                union_ids
            ):
                vertex_id = int(vertex_id)

                tolerance = max(
                    float(
                        options.minimum_visibility_tolerance
                    ),
                    float(
                        options.visibility_tolerance_fraction
                    )
                    * float(
                        local_edge_scales[
                            vertex_id
                        ]
                    ),
                )

                target_position = positions[
                    vertex_id
                ]

                target_faces = connected_faces[
                    vertex_id
                ]

                for joint_index in range(
                    len(influences)
                ):
                    visibility_test_count += 1

                    visibility[
                        union_row,
                        joint_index,
                    ] = _joint_can_see_vertex(
                        mesh_fn=mesh_fn,
                        accel_params=accel_params,
                        joint_position=joint_positions[
                            joint_index
                        ],
                        target_position=target_position,
                        target_faces=target_faces,
                        distance_tolerance=tolerance,
                        ray_tolerance=float(
                            options.ray_tolerance
                        ),
                    )

    finally:
        try:
            mesh_fn.freeCachedIntersectionAccelerator()

        except Exception:
            pass

    strict = (
        visibility
        & (
            inward_dots
            <= float(
                options.inward_dot_threshold
            )
        )
    )

    locked_owner_by_vertex, anchor_modes = _assign_unique_anchors(
        influences=influences,
        raw_by_joint=raw_by_joint,
        union_row_by_vertex=union_row_by_vertex,
        scores=scores,
        visibility=visibility,
        strict=strict,
    )

    owner_by_vertex: Dict[int, int] = {}

    fallback_vertex_count = 0

    for union_row, vertex_id in enumerate(
        union_ids
    ):
        vertex_id = int(vertex_id)

        if vertex_id in locked_owner_by_vertex:
            owner_by_vertex[
                vertex_id
            ] = int(
                locked_owner_by_vertex[
                    vertex_id
                ]
            )

            continue

        strict_joint_ids = np.where(
            strict[
                union_row
            ]
        )[0]

        if strict_joint_ids.size:
            owner_index = _best_joint(
                scores=scores[
                    union_row
                ],
                candidate_joint_ids=strict_joint_ids,
            )

        else:
            visible_joint_ids = np.where(
                visibility[
                    union_row
                ]
            )[0]

            if visible_joint_ids.size:
                owner_index = _best_joint(
                    scores=scores[
                        union_row
                    ],
                    candidate_joint_ids=visible_joint_ids,
                )

            else:
                # This should be rare. Keep it visible in diagnostics.
                fallback_vertex_count += 1

                owner_index = int(
                    np.argmin(
                        scores[
                            union_row
                        ]
                    )
                )

        owner_by_vertex[
            vertex_id
        ] = owner_index

    won_before_filter: List[Set[int]] = [
        set()
        for _ in influences
    ]

    for vertex_id, owner_index in owner_by_vertex.items():
        won_before_filter[
            owner_index
        ].add(
            vertex_id
        )

    anchor_by_joint = {
        owner_index: vertex_id
        for vertex_id, owner_index
        in locked_owner_by_vertex.items()
    }

    resolved_by_joint: List[Set[int]] = [
        set()
        for _ in influences
    ]

    removed_disconnected_counts = [
        0
        for _ in influences
    ]

    for joint_index in range(
        len(influences)
    ):
        owned_vertices = won_before_filter[
            joint_index
        ]

        anchor_vertex_id = anchor_by_joint[
            joint_index
        ]

        anchor_component = _component_containing_anchor(
            candidate_ids=owned_vertices,
            anchor_vertex_id=anchor_vertex_id,
            adjacency=adjacency,
        )

        resolved_by_joint[
            joint_index
        ] = anchor_component

        removed_disconnected_counts[
            joint_index
        ] = (
            len(owned_vertices)
            - len(anchor_component)
        )

    diagnostics = []
    invalid_diagnostics = []

    for joint_index, joint in enumerate(
        influences
    ):
        raw_candidates = raw_by_joint[
            joint_index
        ]

        strict_visible_raw_count = 0
        relaxed_visible_raw_count = 0

        for vertex_id in raw_candidates:
            union_row = union_row_by_vertex[
                vertex_id
            ]

            if strict[
                union_row,
                joint_index,
            ]:
                strict_visible_raw_count += 1

            elif visibility[
                union_row,
                joint_index,
            ]:
                relaxed_visible_raw_count += 1

        anchor_vertex_id = anchor_by_joint[
            joint_index
        ]

        anchor_row = union_row_by_vertex[
            anchor_vertex_id
        ]

        anchor_score = float(
            scores[
                anchor_row,
                joint_index,
            ]
        )

        resolved_count = len(
            resolved_by_joint[
                joint_index
            ]
        )

        messages = []

        if resolved_count < int(
            options.minimum_resolved_seed_count
        ):
            messages.append(
                "only {} connected seeds remain".format(
                    resolved_count
                )
            )

        valid = not messages

        diagnostic = JointCompetitionDiagnostic(
            joint=joint,

            raw_candidate_count=len(
                raw_candidates
            ),

            strict_visible_raw_count=(
                strict_visible_raw_count
            ),

            relaxed_visible_raw_count=(
                relaxed_visible_raw_count
            ),

            won_before_component_filter=len(
                won_before_filter[
                    joint_index
                ]
            ),

            resolved_seed_count=resolved_count,

            removed_disconnected_count=(
                removed_disconnected_counts[
                    joint_index
                ]
            ),

            anchor_vertex_id=anchor_vertex_id,

            anchor_mode=anchor_modes[
                joint_index
            ],

            anchor_score=anchor_score,

            valid=valid,

            messages=tuple(
                messages
            ),
        )

        diagnostics.append(
            diagnostic
        )

        if not valid:
            invalid_diagnostics.append(
                diagnostic
            )

    if (
        invalid_diagnostics
        and options.fail_on_invalid_joint
    ):
        lines = [
            "Global joint seed competition failed:",
            "",
        ]

        for diagnostic in invalid_diagnostics:
            lines.append(
                "{}: {}".format(
                    diagnostic.joint,
                    "; ".join(
                        diagnostic.messages
                    ),
                )
            )

        raise RuntimeError(
            "\n".join(
                lines
            )
        )

    resolved_seed_vertex_ids = {
        joint: tuple(
            sorted(
                resolved_by_joint[
                    joint_index
                ]
            )
        )
        for joint_index, joint
        in enumerate(influences)
    }

    anchor_vertex_ids = {
        joint: int(
            anchor_by_joint[
                joint_index
            ]
        )
        for joint_index, joint
        in enumerate(influences)
    }

    resolved_union = set()

    for resolved_ids in resolved_by_joint:
        resolved_union.update(
            resolved_ids
        )

    return CompetitiveSeedResult(
        mesh_shape=mesh_shape,
        influences=influences,

        resolved_seed_vertex_ids=(
            resolved_seed_vertex_ids
        ),

        anchor_vertex_ids=(
            anchor_vertex_ids
        ),

        diagnostics=tuple(
            diagnostics
        ),

        raw_unique_candidate_count=len(
            raw_union
        ),

        resolved_unique_seed_count=len(
            resolved_union
        ),

        visibility_test_count=(
            visibility_test_count
        ),

        visibility_fallback_vertex_count=(
            fallback_vertex_count
        ),

        elapsed_seconds=(
            time.perf_counter()
            - started
        ),
    )


def select_competitive_joint_seeds(
    result: CompetitiveSeedResult,
    joint: str,
) -> None:
    joint_path = _resolve_result_joint(
        result,
        joint,
    )

    components = _vertex_components(
        mesh_shape=result.mesh_shape,
        vertex_ids=result.resolved_seed_vertex_ids[
            joint_path
        ],
    )

    cmds.select(
        clear=True
    )

    if components:
        cmds.select(
            components,
            replace=True,
        )


def select_competitive_anchor(
    result: CompetitiveSeedResult,
    joint: str,
) -> None:
    joint_path = _resolve_result_joint(
        result,
        joint,
    )

    vertex_id = result.anchor_vertex_ids[
        joint_path
    ]

    components = _vertex_components(
        mesh_shape=result.mesh_shape,
        vertex_ids=(
            vertex_id,
        ),
    )

    cmds.select(
        components,
        replace=True,
    )


def create_competitive_seed_sets(
    result: CompetitiveSeedResult,
    prefix: str = "AD_v26_competitiveSeed",
) -> List[str]:
    created_sets = []

    for joint in result.influences:
        short_name = joint.split(
            "|"
        )[-1]

        set_name = "{}_{}".format(
            prefix,
            short_name,
        )

        if cmds.objExists(
            set_name
        ):
            cmds.delete(
                set_name
            )

        components = _vertex_components(
            mesh_shape=result.mesh_shape,
            vertex_ids=result.resolved_seed_vertex_ids[
                joint
            ],
        )

        created_sets.append(
            cmds.sets(
                components,
                name=set_name,
            )
        )

    return created_sets


def print_competitive_seed_report(
    result: CompetitiveSeedResult,
) -> None:
    print(
        "\n"
        "[AD Skin Tool v2.6 Global Joint Competition]"
    )

    print(
        "Mesh:",
        result.mesh_shape,
    )

    print(
        "Joints:",
        len(
            result.influences
        ),
    )

    print(
        "Raw unique candidates:",
        result.raw_unique_candidate_count,
    )

    print(
        "Resolved unique seeds:",
        result.resolved_unique_seed_count,
    )

    print(
        "Visibility tests:",
        result.visibility_test_count,
    )

    print(
        "Visibility fallback vertices:",
        result.visibility_fallback_vertex_count,
    )

    print(
        "Elapsed seconds:",
        round(
            result.elapsed_seconds,
            3,
        ),
    )

    for diagnostic in result.diagnostics:
        print(
            "\nJoint:",
            diagnostic.joint,
        )

        print(
            "  raw candidates:",
            diagnostic.raw_candidate_count,
        )

        print(
            "  strict visible raw:",
            diagnostic.strict_visible_raw_count,
        )

        print(
            "  relaxed visible raw:",
            diagnostic.relaxed_visible_raw_count,
        )

        print(
            "  won before component filter:",
            diagnostic.won_before_component_filter,
        )

        print(
            "  resolved connected seeds:",
            diagnostic.resolved_seed_count,
        )

        print(
            "  removed disconnected:",
            diagnostic.removed_disconnected_count,
        )

        print(
            "  anchor:",
            diagnostic.anchor_vertex_id,
        )

        print(
            "  anchor mode:",
            diagnostic.anchor_mode,
        )

        print(
            "  anchor score:",
            round(
                diagnostic.anchor_score,
                6,
            ),
        )

        print(
            "  valid:",
            diagnostic.valid,
        )

        for message in diagnostic.messages:
            print(
                "  note:",
                message,
            )


def _build_score_matrices(
    vertex_positions: np.ndarray,
    vertex_normals: np.ndarray,
    joint_positions: np.ndarray,
    normal_alignment_weight: float,
) -> Tuple[np.ndarray, np.ndarray]:
    to_joint = (
        joint_positions[
            np.newaxis,
            :,
            :
        ]
        - vertex_positions[
            :,
            np.newaxis,
            :
        ]
    )

    distances = np.linalg.norm(
        to_joint,
        axis=2,
    )

    safe_distances = np.maximum(
        distances,
        1e-12,
    )

    directions = (
        to_joint
        / safe_distances[
            :,
            :,
            np.newaxis,
        ]
    )

    inward_dots = np.einsum(
        "vji,vi->vj",
        directions,
        vertex_normals,
    )

    alignment_error = (
        0.5
        * (
            1.0
            + np.clip(
                inward_dots,
                -1.0,
                1.0,
            )
        )
    )

    # Absolute world-space distance is deliberately used.
    #
    # Do not normalize by each joint's local radius because that makes
    # scores from different joints incomparable.
    scores = (
        distances
        * (
            1.0
            + float(
                normal_alignment_weight
            )
            * alignment_error
            * alignment_error
        )
    )

    return (
        scores,
        inward_dots,
    )


def _assign_unique_anchors(
    influences: Sequence[str],
    raw_by_joint: List[Set[int]],
    union_row_by_vertex: Dict[int, int],
    scores: np.ndarray,
    visibility: np.ndarray,
    strict: np.ndarray,
) -> Tuple[
    Dict[int, int],
    Dict[int, str],
]:
    pairs = []

    for joint_index in range(
        len(influences)
    ):
        for vertex_id in raw_by_joint[
            joint_index
        ]:
            row = union_row_by_vertex[
                vertex_id
            ]

            if strict[
                row,
                joint_index,
            ]:
                mode_rank = 0
                mode_name = "strict-visible"

            elif visibility[
                row,
                joint_index,
            ]:
                mode_rank = 1
                mode_name = "relaxed-visible"

            else:
                mode_rank = 2
                mode_name = "visibility-fallback"

            pairs.append(
                (
                    mode_rank,
                    float(
                        scores[
                            row,
                            joint_index,
                        ]
                    ),
                    int(
                        joint_index
                    ),
                    int(
                        vertex_id
                    ),
                    mode_name,
                )
            )

    pairs.sort()

    assigned_joints = set()
    assigned_vertices = set()

    locked_owner_by_vertex = {}
    anchor_modes = {}

    for (
        _mode_rank,
        _score,
        joint_index,
        vertex_id,
        mode_name,
    ) in pairs:
        if joint_index in assigned_joints:
            continue

        if vertex_id in assigned_vertices:
            continue

        assigned_joints.add(
            joint_index
        )

        assigned_vertices.add(
            vertex_id
        )

        locked_owner_by_vertex[
            vertex_id
        ] = joint_index

        anchor_modes[
            joint_index
        ] = mode_name

        if len(
            assigned_joints
        ) == len(
            influences
        ):
            break

    missing = [
        influences[
            joint_index
        ]
        for joint_index in range(
            len(influences)
        )
        if joint_index not in assigned_joints
    ]

    if missing:
        raise RuntimeError(
            "Could not reserve unique anchors for:\n{}".format(
                "\n".join(
                    missing
                )
            )
        )

    return (
        locked_owner_by_vertex,
        anchor_modes,
    )


def _best_joint(
    scores: np.ndarray,
    candidate_joint_ids: np.ndarray,
) -> int:
    candidate_scores = scores[
        candidate_joint_ids
    ]

    local_index = int(
        np.argmin(
            candidate_scores
        )
    )

    return int(
        candidate_joint_ids[
            local_index
        ]
    )


def _joint_can_see_vertex(
    mesh_fn,
    accel_params,
    joint_position: np.ndarray,
    target_position: np.ndarray,
    target_faces: Set[int],
    distance_tolerance: float,
    ray_tolerance: float,
) -> bool:
    vector = (
        target_position
        - joint_position
    )

    target_distance = float(
        np.linalg.norm(
            vector
        )
    )

    if target_distance <= 1e-12:
        return True

    direction = (
        vector
        / target_distance
    )

    try:
        hit = mesh_fn.closestIntersection(
            om.MFloatPoint(
                float(
                    joint_position[0]
                ),
                float(
                    joint_position[1]
                ),
                float(
                    joint_position[2]
                ),
            ),
            om.MFloatVector(
                float(
                    direction[0]
                ),
                float(
                    direction[1]
                ),
                float(
                    direction[2]
                ),
            ),
            om.MSpace.kWorld,
            float(
                target_distance
                + distance_tolerance
            ),
            False,
            accelParams=accel_params,
            tolerance=float(
                ray_tolerance
            ),
        )

    except RuntimeError:
        return False

    if not hit:
        return False

    hit_point = hit[0]
    hit_distance = float(
        hit[1]
    )
    hit_face_id = int(
        hit[2]
    )

    hit_position = np.asarray(
        [
            hit_point.x,
            hit_point.y,
            hit_point.z,
        ],
        dtype=np.float64,
    )

    hit_to_target_distance = float(
        np.linalg.norm(
            hit_position
            - target_position
        )
    )

    reaches_target_distance = (
        hit_distance
        >= target_distance
        - distance_tolerance
    )

    reaches_target_position = (
        hit_to_target_distance
        <= distance_tolerance
    )

    hits_target_face = (
        hit_face_id
        in target_faces
    )

    return (
        hits_target_face
        and (
            reaches_target_distance
            or reaches_target_position
        )
    )


def _connected_faces_by_vertex(
    mesh_dag_path,
    vertex_count: int,
) -> List[Set[int]]:
    result = [
        set()
        for _ in range(
            vertex_count
        )
    ]

    iterator = om.MItMeshVertex(
        mesh_dag_path
    )

    while not iterator.isDone():
        vertex_id = int(
            iterator.index()
        )

        result[
            vertex_id
        ] = {
            int(face_id)
            for face_id
            in iterator.getConnectedFaces()
        }

        iterator.next()

    return result


def _local_edge_scales(
    adjacency,
) -> np.ndarray:
    result = np.ones(
        len(adjacency),
        dtype=np.float64,
    )

    all_edge_lengths = []

    for vertex_id, neighbors in enumerate(
        adjacency
    ):
        lengths = [
            float(edge_length)
            for _, edge_length
            in neighbors
            if float(edge_length) > 1e-12
        ]

        if lengths:
            result[
                vertex_id
            ] = float(
                np.median(
                    np.asarray(
                        lengths,
                        dtype=np.float64,
                    )
                )
            )

            all_edge_lengths.extend(
                lengths
            )

    if all_edge_lengths:
        global_scale = float(
            np.median(
                np.asarray(
                    all_edge_lengths,
                    dtype=np.float64,
                )
            )
        )

        invalid = result <= 1e-12
        result[
            invalid
        ] = global_scale

    return result


def _component_containing_anchor(
    candidate_ids: Set[int],
    anchor_vertex_id: int,
    adjacency,
) -> Set[int]:
    if anchor_vertex_id not in candidate_ids:
        raise RuntimeError(
            "Protected anchor is not present in its owner's candidate set."
        )

    visited = {
        int(
            anchor_vertex_id
        )
    }

    stack = [
        int(
            anchor_vertex_id
        )
    ]

    while stack:
        vertex_id = stack.pop()

        for neighbor_id, _ in adjacency[
            vertex_id
        ]:
            neighbor_id = int(
                neighbor_id
            )

            if neighbor_id not in candidate_ids:
                continue

            if neighbor_id in visited:
                continue

            visited.add(
                neighbor_id
            )

            stack.append(
                neighbor_id
            )

    return visited


def _validate_vertex_ids(
    vertex_ids: Set[int],
    vertex_count: int,
    joint: str,
) -> None:
    invalid = [
        vertex_id
        for vertex_id in vertex_ids
        if (
            vertex_id < 0
            or vertex_id >= vertex_count
        )
    ]

    if invalid:
        raise RuntimeError(
            "Invalid candidate vertex IDs for joint:\n{}\n{}".format(
                joint,
                invalid[:20],
            )
        )


def _resolve_result_joint(
    result: CompetitiveSeedResult,
    joint: str,
) -> str:
    matches = cmds.ls(
        joint,
        long=True,
        type="joint",
    ) or []

    if not matches:
        raise RuntimeError(
            "Joint does not exist: {}".format(
                joint
            )
        )

    joint_path = matches[0]

    if joint_path not in result.resolved_seed_vertex_ids:
        raise RuntimeError(
            "Joint was not included in this result:\n{}".format(
                joint_path
            )
        )

    return joint_path


def _vertex_components(
    mesh_shape: str,
    vertex_ids,
) -> List[str]:
    parents = cmds.listRelatives(
        mesh_shape,
        parent=True,
        fullPath=True,
    ) or []

    mesh_name = (
        parents[0]
        if parents
        else mesh_shape
    )

    return [
        "{}.vtx[{}]".format(
            mesh_name,
            int(
                vertex_id
            ),
        )
        for vertex_id in vertex_ids
    ]


def _validate_options(
    options: JointCompetitionOptions,
) -> None:
    if not -1.0 <= float(
        options.inward_dot_threshold
    ) <= 1.0:
        raise ValueError(
            "inward_dot_threshold must be between -1.0 and 1.0."
        )

    if float(
        options.normal_alignment_weight
    ) < 0.0:
        raise ValueError(
            "normal_alignment_weight cannot be negative."
        )

    if float(
        options.ray_tolerance
    ) <= 0.0:
        raise ValueError(
            "ray_tolerance must be positive."
        )

    if float(
        options.visibility_tolerance_fraction
    ) <= 0.0:
        raise ValueError(
            "visibility_tolerance_fraction must be positive."
        )

    if float(
        options.minimum_visibility_tolerance
    ) <= 0.0:
        raise ValueError(
            "minimum_visibility_tolerance must be positive."
        )

    if int(
        options.minimum_resolved_seed_count
    ) < 1:
        raise ValueError(
            "minimum_resolved_seed_count must be at least 1."
        )